// <auto-generated />
namespace SawingFactory.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_width_from_material_roll : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_width_from_material_roll));
        
        string IMigrationMetadata.Id
        {
            get { return "201808010607358_remove_width_from_material_roll"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
