// <auto-generated />
namespace SawingFactory.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fix_produced_product_key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_produced_product_key));
        
        string IMigrationMetadata.Id
        {
            get { return "201807311806517_fix_produced_product_key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
