// <auto-generated />
namespace SawingFactory.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_auto_increment_to_order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_auto_increment_to_order));
        
        string IMigrationMetadata.Id
        {
            get { return "201808011336039_add_auto_increment_to_order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
